--MEM_ID 유니크 속성 추가
ALTER TABLE T_MEMBER ADD CONSTRAINT UQ_MEM_ID UNIQUE(MEM_ID);

-- 회원 관리

--SQ : MEM_SQ

CREATE SEQUENCE MEM_SQ
INCREMENT BY 1
START WITH 1
NOCACHE;

CREATE TABLE T_MEMBER (
    MEM_IDX		NUMBER(10,0) 	PRIMARY KEY,
    MEM_ID		VARCHAR2(20)	UNIQUE,
    MEM_PW		VARCHAR2(100),
    MEM_NAME 		VARCHAR2(20),
    MEM_CATE		VARCHAR2(1) 	NOT NULL,
    MEM_PHONE		VARCHAR2(15),
    MEM_BIRTH		VARCHAR2(10),
    MEM_GENDER		CHAR(1),
    MEM_IMAGE		CLOB,
    MEM_ADDRESS		VARCHAR2(150),
    MEM_NATIONALITY	VARCHAR2(20),
    MEM_REG_IP		VARCHAR2(30),
    MEM_REG_DT		DATE,
    MEM_MOD_DT		DATE,
    MEM_LAST_LOGIN	DATE,
    MEM_LEAVE_FL	CHAR(1),
    MEM_LEAVE_DT	DATE,
    MAILLING_FL		VARCHAR2(2),
    SMS_FL		VARCHAR2(2),
    AUTH_STATUS		CHAR(1) 	DEFAULT '0'
);
